version: "3.8"

services:
  tenant-system:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/TenantSystem
      - /TenantSystem/node_modules # Prevent overwriting node_modules
    command: ["bun", "run", "start"]
