/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthImport } from './routes/_auth'
import { Route as AdminRouteImport } from './routes/admin/route'
import { Route as IndexImport } from './routes/index'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as AdminTenantImport } from './routes/admin/tenant'
import { Route as AdminPropertyImport } from './routes/admin/property'
import { Route as AdminCreatePropertyImport } from './routes/admin/create-property'
import { Route as AdminCreateBillImport } from './routes/admin/create-bill'
import { Route as AdminBillImport } from './routes/admin/bill'
import { Route as AuthenticatedProfileImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedExpenseImport } from './routes/_authenticated/expense'
import { Route as AuthenticatedCreateExpenseImport } from './routes/_authenticated/create-expense'
import { Route as AuthSignupImport } from './routes/_auth/signup'
import { Route as AuthLoginImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordImport } from './routes/_auth/forgot-password'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AdminRouteRoute = AdminRouteImport.update({
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AdminTenantRoute = AdminTenantImport.update({
  path: '/tenant',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminPropertyRoute = AdminPropertyImport.update({
  path: '/property',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminCreatePropertyRoute = AdminCreatePropertyImport.update({
  path: '/create-property',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminCreateBillRoute = AdminCreateBillImport.update({
  path: '/create-bill',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminBillRoute = AdminBillImport.update({
  path: '/bill',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AuthenticatedProfileRoute = AuthenticatedProfileImport.update({
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedExpenseRoute = AuthenticatedExpenseImport.update({
  path: '/expense',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedCreateExpenseRoute = AuthenticatedCreateExpenseImport.update(
  {
    path: '/create-expense',
    getParentRoute: () => AuthenticatedRoute,
  } as any,
)

const AuthSignupRoute = AuthSignupImport.update({
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

const AuthForgotPasswordRoute = AuthForgotPasswordImport.update({
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordImport
      parentRoute: typeof AuthImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof AuthImport
    }
    '/_authenticated/create-expense': {
      id: '/_authenticated/create-expense'
      path: '/create-expense'
      fullPath: '/create-expense'
      preLoaderRoute: typeof AuthenticatedCreateExpenseImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/expense': {
      id: '/_authenticated/expense'
      path: '/expense'
      fullPath: '/expense'
      preLoaderRoute: typeof AuthenticatedExpenseImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileImport
      parentRoute: typeof AuthenticatedImport
    }
    '/admin/bill': {
      id: '/admin/bill'
      path: '/bill'
      fullPath: '/admin/bill'
      preLoaderRoute: typeof AdminBillImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/create-bill': {
      id: '/admin/create-bill'
      path: '/create-bill'
      fullPath: '/admin/create-bill'
      preLoaderRoute: typeof AdminCreateBillImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/create-property': {
      id: '/admin/create-property'
      path: '/create-property'
      fullPath: '/admin/create-property'
      preLoaderRoute: typeof AdminCreatePropertyImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/property': {
      id: '/admin/property'
      path: '/property'
      fullPath: '/admin/property'
      preLoaderRoute: typeof AdminPropertyImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/tenant': {
      id: '/admin/tenant'
      path: '/tenant'
      fullPath: '/admin/tenant'
      preLoaderRoute: typeof AdminTenantImport
      parentRoute: typeof AdminRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof AdminRouteImport
    }
  }
}

// Create and export the route tree

interface AdminRouteRouteChildren {
  AdminBillRoute: typeof AdminBillRoute
  AdminCreateBillRoute: typeof AdminCreateBillRoute
  AdminCreatePropertyRoute: typeof AdminCreatePropertyRoute
  AdminPropertyRoute: typeof AdminPropertyRoute
  AdminTenantRoute: typeof AdminTenantRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminBillRoute: AdminBillRoute,
  AdminCreateBillRoute: AdminCreateBillRoute,
  AdminCreatePropertyRoute: AdminCreatePropertyRoute,
  AdminPropertyRoute: AdminPropertyRoute,
  AdminTenantRoute: AdminTenantRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedCreateExpenseRoute: typeof AuthenticatedCreateExpenseRoute
  AuthenticatedExpenseRoute: typeof AuthenticatedExpenseRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCreateExpenseRoute: AuthenticatedCreateExpenseRoute,
  AuthenticatedExpenseRoute: AuthenticatedExpenseRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/create-expense': typeof AuthenticatedCreateExpenseRoute
  '/expense': typeof AuthenticatedExpenseRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/admin/bill': typeof AdminBillRoute
  '/admin/create-bill': typeof AdminCreateBillRoute
  '/admin/create-property': typeof AdminCreatePropertyRoute
  '/admin/property': typeof AdminPropertyRoute
  '/admin/tenant': typeof AdminTenantRoute
  '/admin/': typeof AdminIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '': typeof AuthRouteWithChildren
  '/about': typeof AboutRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/create-expense': typeof AuthenticatedCreateExpenseRoute
  '/expense': typeof AuthenticatedExpenseRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/admin/bill': typeof AdminBillRoute
  '/admin/create-bill': typeof AdminCreateBillRoute
  '/admin/create-property': typeof AdminCreatePropertyRoute
  '/admin/property': typeof AdminPropertyRoute
  '/admin/tenant': typeof AdminTenantRoute
  '/admin': typeof AdminIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_authenticated/create-expense': typeof AuthenticatedCreateExpenseRoute
  '/_authenticated/expense': typeof AuthenticatedExpenseRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/admin/bill': typeof AdminBillRoute
  '/admin/create-bill': typeof AdminCreateBillRoute
  '/admin/create-property': typeof AdminCreatePropertyRoute
  '/admin/property': typeof AdminPropertyRoute
  '/admin/tenant': typeof AdminTenantRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/admin/': typeof AdminIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | ''
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/create-expense'
    | '/expense'
    | '/profile'
    | '/admin/bill'
    | '/admin/create-bill'
    | '/admin/create-property'
    | '/admin/property'
    | '/admin/tenant'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/create-expense'
    | '/expense'
    | '/profile'
    | '/admin/bill'
    | '/admin/create-bill'
    | '/admin/create-property'
    | '/admin/property'
    | '/admin/tenant'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/_auth'
    | '/_authenticated'
    | '/about'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_authenticated/create-expense'
    | '/_authenticated/expense'
    | '/_authenticated/profile'
    | '/admin/bill'
    | '/admin/create-bill'
    | '/admin/create-property'
    | '/admin/property'
    | '/admin/tenant'
    | '/_authenticated/'
    | '/admin/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin",
        "/_auth",
        "/_authenticated",
        "/about"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin": {
      "filePath": "admin/route.tsx",
      "children": [
        "/admin/bill",
        "/admin/create-bill",
        "/admin/create-property",
        "/admin/property",
        "/admin/tenant",
        "/admin/"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/forgot-password",
        "/_auth/login",
        "/_auth/signup"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/create-expense",
        "/_authenticated/expense",
        "/_authenticated/profile",
        "/_authenticated/"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/_auth/forgot-password": {
      "filePath": "_auth/forgot-password.tsx",
      "parent": "/_auth"
    },
    "/_auth/login": {
      "filePath": "_auth/login.tsx",
      "parent": "/_auth"
    },
    "/_auth/signup": {
      "filePath": "_auth/signup.tsx",
      "parent": "/_auth"
    },
    "/_authenticated/create-expense": {
      "filePath": "_authenticated/create-expense.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/expense": {
      "filePath": "_authenticated/expense.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/profile": {
      "filePath": "_authenticated/profile.tsx",
      "parent": "/_authenticated"
    },
    "/admin/bill": {
      "filePath": "admin/bill.tsx",
      "parent": "/admin"
    },
    "/admin/create-bill": {
      "filePath": "admin/create-bill.tsx",
      "parent": "/admin"
    },
    "/admin/create-property": {
      "filePath": "admin/create-property.tsx",
      "parent": "/admin"
    },
    "/admin/property": {
      "filePath": "admin/property.tsx",
      "parent": "/admin"
    },
    "/admin/tenant": {
      "filePath": "admin/tenant.tsx",
      "parent": "/admin"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/admin/": {
      "filePath": "admin/index.tsx",
      "parent": "/admin"
    }
  }
}
ROUTE_MANIFEST_END */
