name: Lint Code Base

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Super Linter
        uses: super-linter/super-linter@v7.3.0
        env:
          RUN_LOCAL: true
